/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package employeerating.dialog;

import employeerating.DbConnection;
import employeerating.model.CriteriaModel;
import java.awt.Frame;
import javax.swing.JDialog;

/**
 *
 * @author macbookpro
 */
public class CriteriaDialog extends JDialog {

    /**
     * Creates new form CriteriaDialog
     *
     * @param parent
     * @param modal
     */
    static String criteriaIndex;
    private CriteriaModel criteriaModel;

    public CriteriaDialog(Frame parent, boolean modal, String criteriaIndex) {
        super(parent, modal);
        initComponents();
        if (!criteriaIndex.isEmpty()) {
            CriteriaDialog.criteriaIndex = criteriaIndex;
            getCriteriaByIndex(criteriaIndex);
        } else {
            CriteriaDialog.criteriaIndex = "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCriteriaName = new javax.swing.JTextField();
        tfCriteriaAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCriteriaDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Kriteria");

        jLabel2.setText("Bobot");

        jLabel3.setText("Deskripsi");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCriteriaAmount)
                    .addComponent(tfCriteriaName)
                    .addComponent(tfCriteriaDesc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(btnOk)
                            .addComponent(errorLabel))
                        .addGap(0, 401, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCriteriaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCriteriaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCriteriaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String criteriaName = tfCriteriaName.getText();
        String criteriaAmount = tfCriteriaAmount.getText();
        String criteriaDesc = tfCriteriaDesc.getText();
        if (criteriaName.isEmpty()) {
            errorLabel.setText("Error: Field Nama cannot be empty");
        }
        if (criteriaAmount.isEmpty()) {
            errorLabel.setText("Error: Field Bobot cannot be empty");
        }
        if (criteriaDesc.isEmpty()) {
            errorLabel.setText("Error: Field Deskripsi cannot be empty");
        } else {
            new DbConnection().UpdateCriteriaById(criteriaModel.getCriteriaId(),
                    criteriaModel.getCriteriaName(),
                    criteriaModel.getCriteriaAmount(),
                    criteriaModel.getCriteriaDesc());
            setVisible(false);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriteriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriteriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriteriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriteriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CriteriaDialog dialog = new CriteriaDialog(new javax.swing.JFrame(), true, criteriaIndex);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfCriteriaAmount;
    private javax.swing.JTextField tfCriteriaDesc;
    private javax.swing.JTextField tfCriteriaName;
    // End of variables declaration//GEN-END:variables

    private void getCriteriaByIndex(String criteriaIndex) {
        criteriaModel = new DbConnection().SelectCriteriaByIndex(criteriaIndex);
        tfCriteriaName.setText(criteriaModel.getCriteriaName());
        tfCriteriaAmount.setText(criteriaModel.getCriteriaAmount());
        tfCriteriaDesc.setText(criteriaModel.getCriteriaDesc());
    }
}
