/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package employeerating.dialog;

import employeerating.DbConnection;
import employeerating.model.EmployeeModel;
import java.awt.Frame;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author macbookpro
 */
public class ScoreDialog extends JDialog {

    static String employeeId;
    private int selectedcbK1 = 0;
    private int selectedcbK2 = 0;
    private int selectedcbK3 = 0;
    private int selectedcbK4 = 0;
    private int selectedcbK5 = 0;
    private EmployeeModel employeeModel;
    Frame parent;

    /**
     * Creates new form EmployeeDialog
     *
     * @param parent
     * @param modal
     * @param newId
     */
    public ScoreDialog(Frame parent, boolean modal, String newId) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        employeeId = newId;
        // define items in a String array:
        String[] languages = new String[]{"Kurang Memuaskan", "Perlu Perbaikan", "Memenuhi Harapan", "Melebihi Harapan", "Luar Biasa"};
        cbK1 = new JComboBox<>(languages);
        cbK2 = new JComboBox<>(languages);
        cbK3 = new JComboBox<>(languages);
        cbK4 = new JComboBox<>(languages);
        cbK5 = new JComboBox<>(languages);
        setEmployeeName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfEmployeeName = new javax.swing.JTextField();
        btnAddRating = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbK1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbK2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbK3 = new javax.swing.JComboBox<>();
        cbK4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbK5 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Karyawan");

        tfEmployeeName.setEnabled(false);

        btnAddRating.setText("OK");
        btnAddRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRatingActionPerformed(evt);
            }
        });

        jLabel5.setText("Disiplin");

        cbK1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kurang Memuaskan", "Perlu Perbaikan", "Memenuhi Harapan", "Melebihi Harapan", "Luar Biasa" }));
        cbK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbK1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Komitmen");

        cbK2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kurang Memuaskan", "Perlu Perbaikan", "Memenuhi Harapan", "Melebihi Harapan", "Luar Biasa" }));
        cbK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbK2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Kreatifitas");

        jLabel8.setText("Prestasi");

        cbK3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kurang Memuaskan", "Perlu Perbaikan", "Memenuhi Harapan", "Melebihi Harapan", "Luar Biasa" }));
        cbK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbK3ActionPerformed(evt);
            }
        });

        cbK4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kurang Memuaskan", "Perlu Perbaikan", "Memenuhi Harapan", "Melebihi Harapan", "Luar Biasa" }));
        cbK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbK4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Loyalitas");

        cbK5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kurang Memuaskan", "Perlu Perbaikan", "Memenuhi Harapan", "Melebihi Harapan", "Luar Biasa" }));
        cbK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbK5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmployeeName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(btnAddRating)
                                    .addComponent(cbK1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addComponent(cbK2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 67, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbK3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbK4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbK5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbK4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbK5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnAddRating)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRatingActionPerformed
        // TODO add your handling code here:
        String employeeName = tfEmployeeName.getText();
        String ratingValue = "{"
                + "\"K1\":" + selectedcbK1 + ","
                + "\"K2\":" + selectedcbK2 + ","
                + "\"K3\":" + selectedcbK3 + ","
                + "\"K4\":" + selectedcbK4 + ","
                + "\"K5\":" + selectedcbK5
                + "}";

        new DbConnection().UpdateRating(employeeModel.employeeId, employeeModel.employeeId, ratingValue, "");
        setVisible(false);

    }//GEN-LAST:event_btnAddRatingActionPerformed

    private void cbK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbK1ActionPerformed
        // TODO add your handling code here:
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        selectedcbK1 = combo.getSelectedIndex();
    }//GEN-LAST:event_cbK1ActionPerformed

    private void cbK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbK2ActionPerformed
        // TODO add your handling code here:
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        selectedcbK2 = combo.getSelectedIndex();
    }//GEN-LAST:event_cbK2ActionPerformed

    private void cbK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbK3ActionPerformed
        // TODO add your handling code here:
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        selectedcbK3 = combo.getSelectedIndex();
    }//GEN-LAST:event_cbK3ActionPerformed

    private void cbK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbK4ActionPerformed
        // TODO add your handling code here:
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        selectedcbK4 = combo.getSelectedIndex();
    }//GEN-LAST:event_cbK4ActionPerformed

    private void cbK5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbK5ActionPerformed
        // TODO add your handling code here:
        JComboBox<String> combo = (JComboBox<String>) evt.getSource();
        selectedcbK5 = combo.getSelectedIndex();
    }//GEN-LAST:event_cbK5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ScoreDialog dialog = new ScoreDialog(new JFrame(), true, employeeId);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRating;
    private javax.swing.JComboBox<String> cbK1;
    private javax.swing.JComboBox<String> cbK2;
    private javax.swing.JComboBox<String> cbK3;
    private javax.swing.JComboBox<String> cbK4;
    private javax.swing.JComboBox<String> cbK5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfEmployeeName;
    // End of variables declaration//GEN-END:variables

    private void setEmployeeName() {
        employeeModel = new DbConnection().SelectEmployeeByIndex(employeeId);
        tfEmployeeName.setText(employeeModel.getEmployeeaName());
    }
}
