/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package employeerating;

import employeerating.dialog.EmployeeDialog;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbookpro
 */
public class EmployeeFrm extends JInternalFrame {

    private final Frame frame;
    private String employeeIdDefault = "E000000000";
    private String newId;

    /**
     * Creates new form HomeFrm
     */
    public EmployeeFrm() {
        initComponents();
        generateDataToTable();

        JInternalFrame internalFrame = this; // Replace with your internal frame

        frame = (Frame) SwingUtilities.getAncestorOfClass(JFrame.class, internalFrame);
        if (frame != null) {
            // You have the frame reference
            System.out.println("Found frame: " + frame.getTitle());
        } else {
            // Frame not found
            System.out.println("Could not find frame for the internal frame.");
        }

    }

    private void generateDataToTable() {
        //data product
        DefaultTableModel rsSelect0 = new DbConnection().SelectListEmployee();
        System.out.println("raw count employee " + rsSelect0.getRowCount());
        String maxId = String.valueOf(rsSelect0.getRowCount() + 1);
        String newEmployeeIdDefault = employeeIdDefault.substring(0, employeeIdDefault.length() - maxId.length());
        newId = newEmployeeIdDefault + maxId;
        tableEmployee.setModel(rsSelect0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        btnAddEmployee = new javax.swing.JButton();

        setSize(new java.awt.Dimension(100, 100));

        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEmployee);

        btnAddEmployee.setText("Tambah Karyawan");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAddEmployee)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(btnAddEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        EmployeeDialog dialog = new EmployeeDialog(frame, true, newId);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAddEmployeeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEmployee;
    // End of variables declaration//GEN-END:variables
}
